/**
 * The word lists behind the blank rule in `vocab-blanks.ts`, as the lint's
 * `scripts/cards/vocab-rules.mjs` holds them.
 */

/** Irregular forms of the words a headword is most often built on. */
export const IRREGULAR: Readonly<Record<string, readonly string[]>> = {
  be: ["am", "is", "are", "was", "were", "been", "being"],
  have: ["has", "had"],
  do: ["does", "did", "done"],
  go: ["goes", "went", "gone"],
  give: ["gave", "given"],
  get: ["got", "gotten"],
  take: ["took", "taken"],
  make: ["made"],
  come: ["came"],
  become: ["became"],
  break: ["broke", "broken"],
  bring: ["brought"],
  buy: ["bought"],
  catch: ["caught"],
  think: ["thought"],
  teach: ["taught"],
  fight: ["fought"],
  seek: ["sought"],
  feel: ["felt"],
  keep: ["kept"],
  sleep: ["slept"],
  leave: ["left"],
  mean: ["meant"],
  deal: ["dealt"],
  meet: ["met"],
  lose: ["lost"],
  send: ["sent"],
  spend: ["spent"],
  lend: ["lent"],
  build: ["built"],
  run: ["ran"],
  sit: ["sat"],
  win: ["won"],
  hold: ["held"],
  find: ["found"],
  tell: ["told"],
  sell: ["sold"],
  say: ["said"],
  pay: ["paid"],
  lay: ["laid"],
  hear: ["heard"],
  see: ["saw", "seen"],
  fall: ["fell", "fallen"],
  stand: ["stood"],
  understand: ["understood"],
  speak: ["spoke", "spoken"],
  throw: ["threw", "thrown"],
  wear: ["wore", "worn"],
  write: ["wrote", "written"],
  drive: ["drove", "driven"],
  ride: ["rode", "ridden"],
  rise: ["rose", "risen"],
  eat: ["ate", "eaten"],
  fly: ["flew", "flown"],
  know: ["knew", "known"],
  grow: ["grew", "grown"],
  blow: ["blew", "blown"],
  draw: ["drew", "drawn"],
  show: ["showed", "shown"],
  begin: ["began", "begun"],
  drink: ["drank", "drunk"],
  ring: ["rang", "rung"],
  sing: ["sang", "sung"],
  swim: ["swam", "swum"],
  hang: ["hung"],
  stick: ["stuck"],
  strike: ["struck"],
  shoot: ["shot"],
  feed: ["fed"],
  lead: ["led"],
  light: ["lit"],
  bite: ["bit", "bitten"],
  hide: ["hid", "hidden"],
  shake: ["shook", "shaken"],
  steal: ["stole", "stolen"],
  choose: ["chose", "chosen"],
  forget: ["forgot", "forgotten"],
  freeze: ["froze", "frozen"],
  wake: ["woke", "woken"],
  child: ["children"],
  person: ["people"],
  man: ["men"],
  woman: ["women"],
  foot: ["feet"],
  tooth: ["teeth"],
  mouse: ["mice"],
  good: ["better", "best"],
  well: ["better", "best"],
  bad: ["worse", "worst"],
  far: ["farther", "farthest", "further", "furthest"],
  many: ["more", "most"],
  much: ["more", "most"],
  little: ["less", "least"],
};

/** Words that stand in for one another: `a` for `an`, and each set of personal pronouns. */
export const INTERCHANGEABLE: readonly (readonly string[])[] = [
  ["a", "an"],
  ["i", "you", "he", "she", "it", "we", "they"],
  ["me", "you", "him", "her", "it", "us", "them"],
  ["my", "your", "his", "her", "its", "our", "their"],
  [
    "myself",
    "yourself",
    "himself",
    "herself",
    "itself",
    "ourselves",
    "yourselves",
    "themselves",
  ],
];

/**
 * Placeholders a headword may name (`make up one's mind`): a blank may skip
 * one, or blank the word that fills it — any word, unless a set is listed.
 */
export const PLACEHOLDERS: Readonly<Record<string, readonly string[] | null>> = {
  "one's": INTERCHANGEABLE[3] ?? null,
  "someone's": null,
  "somebody's": null,
  oneself: INTERCHANGEABLE[4] ?? null,
  someone: null,
  somebody: null,
  something: null,
  sb: null,
  sth: null,
};
