import { errorResponseSchema } from "./errors";
import {
  answerResultSchema,
  dotSchema,
  gradeKeysSchema,
  levelModeSchema,
  passSchema,
  reachTopicSchema,
  reachViewSchema,
  ringProgressSchema,
  roundKindSchema,
  settingsSchema,
  subtopicRefSchema,
} from "./primitives";
import {
  breakdownTopicSchema,
  historySchema,
  homePreviewSchema,
  homeStateSchema,
  homeViewSchema,
  recordsViewSchema,
  settingsPageViewSchema,
  streakViewSchema,
  titleGroupSchema,
  topicInfoSchema,
  weakPointsSchema,
} from "./query-views";
import {
  answerSchema,
  answersRequestSchema,
  levelChoiceSchema,
  profilePatchSchema,
  settingsPatchSchema,
  startRoundRequestSchema,
} from "./requests";
import {
  drillCardSchema,
  growthRowSchema,
  growthSchema,
  levelViewSchema,
  profileSchema,
  reviewRowSchema,
  roundPayloadSchema,
  roundSummarySchema,
  settingsViewSchema,
  totalsViewSchema,
} from "./views";

/**
 * The schemas the document names under `components.schemas`, by the name a
 * generated client gives each type. A schema listed here is written once and
 * referenced wherever it is used; one left out is inlined. Every request and
 * response body has to be listed, which `openApiDocument` checks.
 */
export const COMPONENTS = {
  RoundKind: roundKindSchema,
  Pass: passSchema,
  AnswerResult: answerResultSchema,
  SubtopicRef: subtopicRefSchema,
  GradeKeys: gradeKeysSchema,
  Settings: settingsSchema,
  Dot: dotSchema,
  RingProgress: ringProgressSchema,
  ReachTopic: reachTopicSchema,
  ReachView: reachViewSchema,
  StartRoundRequest: startRoundRequestSchema,
  Answer: answerSchema,
  AnswersRequest: answersRequestSchema,
  SettingsPatch: settingsPatchSchema,
  LevelMode: levelModeSchema,
  LevelChoice: levelChoiceSchema,
  ProfilePatch: profilePatchSchema,
  DrillCard: drillCardSchema,
  RoundPayload: roundPayloadSchema,
  GrowthRow: growthRowSchema,
  Growth: growthSchema,
  ReviewRow: reviewRowSchema,
  TotalsView: totalsViewSchema,
  RoundSummary: roundSummarySchema,
  SettingsView: settingsViewSchema,
  LevelView: levelViewSchema,
  Profile: profileSchema,
  StreakView: streakViewSchema,
  HomeState: homeStateSchema,
  HomePreview: homePreviewSchema,
  HomeView: homeViewSchema,
  BreakdownTopic: breakdownTopicSchema,
  TitleGroup: titleGroupSchema,
  WeakPoints: weakPointsSchema,
  RecordsView: recordsViewSchema,
  TopicInfo: topicInfoSchema,
  SettingsPageView: settingsPageViewSchema,
  History: historySchema,
  ErrorResponse: errorResponseSchema,
} as const;
