import {
  vocabPageRequestSchema,
  vocabPreparationSchema,
  vocabPageSchema,
  vocabPagedAnswerSchema,
  vocabPagedAnswersRequestSchema,
  vocabPagedSummarySchema,
} from "./vocab-pages";
import { errorResponseSchema } from "./errors";
import {
  answerResultSchema,
  dotSchema,
  drillNewPerDaySchema,
  drillReviewsPerDaySchema,
  gradeIntervalsSchema,
  gradeKeysPatchSchema,
  gradeKeysSchema,
  gradeKeyTrioSchema,
  levelModeSchema,
  gradeSchema,
  passSchema,
  reachTopicSchema,
  reachViewSchema,
  ringProgressSchema,
  roundKindSchema,
  settingsSchema,
  subtopicRefSchema,
  vocabCategorySchema,
  vocabNewPerDaySchema,
  vocabReviewsPerDaySchema,
} from "./primitives";
import {
  breakdownTopicSchema,
  historySchema,
  homePreviewSchema,
  homeStateSchema,
  homeViewSchema,
  recordsViewSchema,
  settingsPageViewSchema,
  streakViewSchema,
  titleGroupSchema,
  topicInfoSchema,
  weakPointsSchema,
} from "./query-views";
import {
  answerSchema,
  answersRequestSchema,
  levelChoiceSchema,
  profilePatchSchema,
  settingsPatchSchema,
  startRoundRequestSchema,
} from "./requests";
import {
  addCardsRequestSchema,
  cardCandidateSchema,
  cardCandidatesSchema,
  judgmentSchema,
  partnerReplySchema,
  recitalRequestSchema,
  sceneSchema,
  startTalkRequestSchema,
  talkEndedSchema,
  talkOpenedSchema,
  talkViewSchema,
  turnRequestSchema,
  turnResultSchema,
  verdictSchema,
} from "./talk";
import {
  answeredRowSchema,
  drillCardSchema,
  growthRowSchema,
  growthSchema,
  levelViewSchema,
  profileSchema,
  reviewRowSchema,
  roundPayloadSchema,
  roundSummarySchema,
  settingsViewSchema,
  totalsViewSchema,
} from "./views";
import {
  startVocabSessionRequestSchema,
  vocabAgainRowSchema,
  vocabAnswerSchema,
  vocabAnswersRequestSchema,
  vocabCardSchema,
  vocabCategoryViewSchema,
  vocabHubSchema,
  vocabSessionKindSchema,
  vocabSessionSchema,
  vocabSummarySchema,
} from "./vocab";

/**
 * The schemas the document names under `components.schemas`, by the name a
 * generated client gives each type. A schema listed here is written once and
 * referenced wherever it is used; one left out is inlined. Every request and
 * response body has to be listed, which `openApiDocument` checks.
 */
export const COMPONENTS = {
  VocabPageRequest: vocabPageRequestSchema,
  VocabPreparation: vocabPreparationSchema,
  VocabPage: vocabPageSchema,
  VocabPagedAnswer: vocabPagedAnswerSchema,
  VocabPagedAnswersRequest: vocabPagedAnswersRequestSchema,
  VocabPagedSummary: vocabPagedSummarySchema,
  RoundKind: roundKindSchema,
  Pass: passSchema,
  AnswerResult: answerResultSchema,
  SubtopicRef: subtopicRefSchema,
  GradeKeys: gradeKeysSchema,
  GradeKeyTrio: gradeKeyTrioSchema,
  GradeKeysPatch: gradeKeysPatchSchema,
  DrillNewPerDay: drillNewPerDaySchema,
  DrillReviewsPerDay: drillReviewsPerDaySchema,
  Settings: settingsSchema,
  Dot: dotSchema,
  RingProgress: ringProgressSchema,
  ReachTopic: reachTopicSchema,
  ReachView: reachViewSchema,
  StartRoundRequest: startRoundRequestSchema,
  Answer: answerSchema,
  AnswersRequest: answersRequestSchema,
  SettingsPatch: settingsPatchSchema,
  LevelMode: levelModeSchema,
  LevelChoice: levelChoiceSchema,
  ProfilePatch: profilePatchSchema,
  DrillCard: drillCardSchema,
  AnsweredRow: answeredRowSchema,
  RoundPayload: roundPayloadSchema,
  GrowthRow: growthRowSchema,
  Growth: growthSchema,
  ReviewRow: reviewRowSchema,
  TotalsView: totalsViewSchema,
  RoundSummary: roundSummarySchema,
  SettingsView: settingsViewSchema,
  LevelView: levelViewSchema,
  Profile: profileSchema,
  StreakView: streakViewSchema,
  HomeState: homeStateSchema,
  HomePreview: homePreviewSchema,
  HomeView: homeViewSchema,
  BreakdownTopic: breakdownTopicSchema,
  TitleGroup: titleGroupSchema,
  WeakPoints: weakPointsSchema,
  RecordsView: recordsViewSchema,
  TopicInfo: topicInfoSchema,
  SettingsPageView: settingsPageViewSchema,
  History: historySchema,
  StartTalkRequest: startTalkRequestSchema,
  TurnRequest: turnRequestSchema,
  RecitalRequest: recitalRequestSchema,
  Scene: sceneSchema,
  TalkOpened: talkOpenedSchema,
  TalkView: talkViewSchema,
  Verdict: verdictSchema,
  Judgment: judgmentSchema,
  PartnerReply: partnerReplySchema,
  TurnResult: turnResultSchema,
  TalkEnded: talkEndedSchema,
  AddCardsRequest: addCardsRequestSchema,
  CardCandidate: cardCandidateSchema,
  CardCandidates: cardCandidatesSchema,
  Grade: gradeSchema,
  GradeIntervals: gradeIntervalsSchema,
  VocabCategory: vocabCategorySchema,
  VocabNewPerDay: vocabNewPerDaySchema,
  VocabReviewsPerDay: vocabReviewsPerDaySchema,
  VocabSessionKind: vocabSessionKindSchema,
  StartVocabSessionRequest: startVocabSessionRequestSchema,
  VocabAnswer: vocabAnswerSchema,
  VocabAnswersRequest: vocabAnswersRequestSchema,
  VocabCategoryView: vocabCategoryViewSchema,
  VocabHub: vocabHubSchema,
  VocabCard: vocabCardSchema,
  VocabSession: vocabSessionSchema,
  VocabAgainRow: vocabAgainRowSchema,
  VocabSummary: vocabSummarySchema,
  ErrorResponse: errorResponseSchema,
} as const;
