// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type RoundKind = 'placement' | 'today' | 'yesterday' | 'extra';

export type Pass = 'first' | 'retry';

export type AnswerResult = 'ok' | 'ng' | 'timeout';

export type SubtopicRef = {
    topic: string;
    subtopic: string;
};

export type GradeKeys = {
    ok: string;
    ng: string;
};

export type GradeKeyTrio = {
    ok: string;
    ng: string;
    hard: string;
};

export type GradeKeysPatch = {
    ok: string;
    ng: string;
    hard?: string;
};

export type DrillNewPerDay = 0 | 3 | 5 | 10 | 15;

export type DrillReviewsPerDay = 10 | 20 | 30 | 50 | null;

export type Settings = {
    topics: Array<string>;
    focus: Array<SubtopicRef>;
    dailySize: 5 | 10 | 15 | 20 | 30;
    sound: boolean;
    limitSeconds: 15 | 20 | 30 | 45 | 60;
    gradeKeys: GradeKeyTrio;
    newPerDay: DrillNewPerDay;
    reviewsPerDay: DrillReviewsPerDay;
    vocabNewPerDay: VocabNewPerDay;
    vocabReviewsPerDay: VocabReviewsPerDay;
};

export type Dot = {
    day: string;
    state: 'done' | 'gap' | 'missed' | 'upcoming';
};

export type RingProgress = {
    from: number;
    to: number;
    done: number;
    span: number;
};

export type ReachTopic = {
    id: string;
    name: string;
    count: number;
    added: number;
    ring: RingProgress;
};

export type ReachView = {
    topics: Array<ReachTopic>;
    nearest: {
        name: string;
        remaining: number;
    } | null;
    pending?: number;
};

export type StartRoundRequest = {
    roundId: string;
    kind: RoundKind;
};

export type Answer = {
    id: string;
    cardId: string;
    pass: Pass;
    result?: AnswerResult;
    grade?: Grade;
    timedOut?: boolean;
    elapsedMs: number;
    answeredAt?: number;
};

export type AnswersRequest = {
    answers: Array<Answer>;
};

export type SettingsPatch = {
    topics?: Array<string>;
    focus?: Array<SubtopicRef>;
    dailySize?: 5 | 10 | 15 | 20 | 30;
    sound?: boolean;
    limitSeconds?: 15 | 20 | 30 | 45 | 60;
    gradeKeys?: GradeKeysPatch;
    newPerDay?: DrillNewPerDay;
    reviewsPerDay?: DrillReviewsPerDay;
    vocabNewPerDay?: VocabNewPerDay;
    vocabReviewsPerDay?: VocabReviewsPerDay;
};

export type LevelMode = 'auto' | 'manual';

export type LevelChoice = {
    mode: 'auto';
} | {
    mode: 'manual';
    level: number;
};

export type ProfilePatch = {
    timeZone?: string;
    l1?: string;
    target?: string;
    uiLocale?: 'ja';
};

export type DrillCard = {
    id: string;
    topic: string;
    subtopic: string;
    level: number;
    words: number;
    prompt: string;
    text: string;
    alternatives: Array<string>;
    explanation: string;
    limitMs: number;
    paceMs: number;
    fastMs: number;
    intervals: GradeIntervals;
    isNew: boolean;
};

export type AnsweredRow = {
    id: string;
    cardId: string;
    pass: Pass;
    result: AnswerResult;
    grade: Grade;
    timedOut: boolean;
    answeredAt: number;
};

export type RoundPayload = {
    id: string;
    kind: RoundKind;
    day: string;
    portionDay: string | null;
    deck: Array<string>;
    cards: {
        [key: string]: DrillCard;
    };
    answered: Array<AnsweredRow>;
    offset: number;
    total: number;
    retries: boolean;
};

export type GrowthRow = {
    cardId: string;
    prompt: string | null;
    kind: 'faster' | 'fixed';
    deltaMs: number;
};

export type Growth = {
    faster: number;
    fixed: number;
    compared: number;
    firstTime: number;
    rows: Array<GrowthRow>;
};

export type ReviewRow = {
    cardId: string;
    prompt: string | null;
};

export type TotalsView = {
    said: number;
    practicedDays: number;
    last14: Array<{
        day: string;
        count: number;
    }>;
    added: number;
};

export type RoundSummary = {
    roundId: string;
    kind: RoundKind;
    day: string;
    answered: Array<AnsweredRow>;
    yesterday: boolean;
    placement: {
        level: number;
        toeic: string;
        first: boolean;
    } | null;
    growth: Growth;
    review: Array<ReviewRow>;
    streak: {
        value: number;
        restart: boolean;
        changed: boolean;
    };
    week: Array<Dot>;
    filled: string | null;
    difficulty: {
        change: 'up' | 'down';
        toeic: string;
    } | null;
    reach: ReachView;
    titles: Array<string>;
    topicNames: {
        [key: string]: string;
    };
    points: {
        earned: number;
        total: number;
    };
    totals: TotalsView;
    portionCompleted: boolean;
    todayOpen: boolean;
    continueToday: boolean;
};

export type SettingsView = {
    settings: Settings;
    removedFocus: Array<SubtopicRef>;
    completedToday: boolean;
};

export type LevelView = {
    mode: LevelMode;
    level: number | null;
    toeic: string | null;
};

export type Profile = {
    timeZone: string;
    l1: string;
    target: string;
    uiLocale: string;
};

export type StreakView = {
    kind: 'count';
    value: number;
    yesterdayGap: boolean;
} | {
    kind: 'restart';
    longest: number;
};

export type HomeState = {
    kind: 'onboarding';
} | {
    kind: 'placement';
} | {
    kind: 'ready';
    streak: StreakView;
} | {
    kind: 'recover-offer';
    streak: StreakView;
} | {
    kind: 'in-progress';
    portion: 'today' | 'yesterday';
    progress: number;
    target: number;
    resumeKind: RoundKind;
    streak: StreakView;
} | {
    kind: 'done';
    restoresTo: number | null;
    streak: StreakView;
} | {
    kind: 'not-enough';
    available: number;
    streak: StreakView;
};

export type HomePreview = {
    size: number;
    setting: number;
    shortage: boolean;
    reviewCount: number;
    newCount: number;
    focusNames: Array<string>;
    weakNames: Array<string>;
    minutes: number;
};

export type HomeView = {
    state: HomeState;
    week: Array<Dot>;
    today: string;
    preview?: HomePreview;
    todayRounds: number;
    todayCards: number;
    todayLastRoundId?: string;
    dailySize: number;
    dayBoundaryHour: number;
    talkTurns: number;
    sound: boolean;
    gradeKeys: GradeKeyTrio;
    contentError: boolean;
};

export type BreakdownTopic = {
    id: string;
    name: string;
    subtopics: Array<{
        id: string;
        name: string;
        count: number;
    }>;
};

export type TitleGroup = {
    kind: 'streak';
    values: Array<number>;
} | {
    kind: 'reach';
    topic: string;
    name: string;
    values: Array<number>;
};

export type WeakPoints = {
    grammar: Array<{
        id: string;
        name: string;
    }>;
    subtopics: Array<{
        topic: string;
        subtopic: string;
        name: string;
    }>;
};

export type RecordsView = {
    reach: ReachView;
    breakdown: Array<BreakdownTopic>;
    weak: WeakPoints;
    toeic: string | null;
    levelMode: LevelMode;
    suggestedToeic: string | null;
    streak: {
        current: number;
        longest: number;
    };
    calendar: Array<Array<Dot>>;
    said: number;
    practicedDays: number;
    points: number;
    titles: Array<TitleGroup>;
};

export type TopicInfo = {
    id: string;
    name: string;
    subtopics: Array<{
        id: string;
        name: string;
    }>;
};

export type SettingsPageView = {
    settings: Settings;
    options: {
        dailySizes: Array<5 | 10 | 15 | 20 | 30>;
        newPerDay: Array<DrillNewPerDay>;
        reviewsPerDay: Array<DrillReviewsPerDay>;
        limitSeconds: Array<15 | 20 | 30 | 45 | 60>;
        maxFocus: number;
    };
    topics: Array<TopicInfo>;
    /**
     * The same value as `difficulty.toeic`, which a client reads instead. Kept for /v1; removed in /v2.
     *
     * @deprecated
     */
    toeic: string | null;
    difficulty: LevelView;
    levels: Array<{
        level: number;
        toeic: string;
    }>;
};

export type History = {
    seenIds: Array<string>;
    topics: Array<string>;
    focusSubtopics: Array<string>;
    estimatedLevel: number;
};

export type StartTalkRequest = {
    talkId: string;
};

export type TurnRequest = {
    turn: number;
    japanese: string;
    english: string | null;
};

export type RecitalRequest = {
    revealCount: number;
};

export type Scene = {
    partner: string;
    place: string;
    relation: string;
    description: string;
};

export type TalkOpened = {
    talkId: string;
    scene: Scene;
    opening: string;
    turnCount: number;
};

export type TalkView = {
    talkId: string;
    scene: Scene;
    opening: string;
    turnCount: number;
    status: 'open' | 'finished' | 'ended' | 'discarded';
    turns: Array<{
        turn: number;
        japanese: string;
        english: string | null;
        judgment: Judgment;
        reply: string | null;
        closing: boolean;
    }>;
};

export type Verdict = 'fine' | 'corrected' | 'failed';

export type Judgment = {
    verdict: Verdict;
    modelAnswer: string;
    point: string;
};

export type PartnerReply = {
    line: string;
    closing: boolean;
};

export type TurnResult = {
    judgment: Judgment;
    reply: PartnerReply | null;
};

export type TalkEnded = {
    kept: boolean;
};

export type AddCardsRequest = {
    candidates: Array<number>;
};

export type CardCandidate = {
    index: number;
    turn: number;
    cardId: string | null;
    catalog: boolean;
    category: VocabCategory;
    headword: string;
    definition: string;
    example: string;
    example2: string;
    meaning: string;
    inLearning: boolean;
    added: boolean;
};

export type CardCandidates = {
    candidates: Array<CardCandidate>;
};

export type Grade = 'again' | 'hard' | 'good';

export type GradeIntervals = {
    again: number;
    hard: number;
    good: number;
};

export type VocabCategory = 'word' | 'idiom' | 'phrasal-verb' | 'phrase';

export type VocabNewPerDay = 0 | 5 | 10 | 15 | 20 | 30;

export type VocabReviewsPerDay = 50 | 100 | 200 | null;

export type VocabSessionKind = 'today' | 'extra' | 'weak';

export type StartVocabSessionRequest = {
    sessionId: string;
    kind: VocabSessionKind;
    category?: VocabCategory;
};

export type VocabAnswer = {
    id: string;
    cardId: string;
    pass: Pass;
    grade: Grade;
    elapsedMs: number;
    answeredAt?: number;
};

export type VocabAnswersRequest = {
    answers: Array<VocabAnswer>;
};

export type VocabCategoryView = {
    category: VocabCategory;
    due: number;
    new: number;
    learning: number;
    total: number;
};

export type VocabHub = {
    empty: boolean;
    today: {
        due: number;
        new: number;
        minutes: number;
    };
    categories: Array<VocabCategoryView>;
    weak: number;
    tomorrow: number;
};

export type VocabCard = {
    id: string;
    category: VocabCategory;
    level: number;
    definition: string;
    example: string;
    headword: string;
    meaning: string;
    example2: string;
    intervals: GradeIntervals;
    isNew: boolean;
    personal: boolean;
};

export type VocabSession = {
    sessionId: string;
    kind: VocabSessionKind;
    category: VocabCategory | null;
    day: string;
    cards: Array<VocabCard>;
};

export type VocabAgainRow = {
    cardId: string;
    headword: string;
    meaning: string;
};

export type VocabSummary = {
    sessionId: string;
    kind: VocabSessionKind;
    category: VocabCategory | null;
    day: string;
    answered: number;
    new: number;
    again: Array<VocabAgainRow>;
    tomorrow: number;
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
    };
};

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetProfileErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * OK
     */
    200: Profile;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: ProfilePatch;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type UpdateProfileErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * OK
     */
    200: Profile;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsPageView;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: SettingsPatch;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type UpdateSettingsErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: SettingsView;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type UpdateLevelData = {
    body: LevelChoice;
    path?: never;
    query?: never;
    url: '/v1/level';
};

export type UpdateLevelErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type UpdateLevelError = UpdateLevelErrors[keyof UpdateLevelErrors];

export type UpdateLevelResponses = {
    /**
     * OK
     */
    200: LevelView;
};

export type UpdateLevelResponse = UpdateLevelResponses[keyof UpdateLevelResponses];

export type GetHomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/home';
};

export type GetHomeErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetHomeError = GetHomeErrors[keyof GetHomeErrors];

export type GetHomeResponses = {
    /**
     * OK
     */
    200: HomeView;
};

export type GetHomeResponse = GetHomeResponses[keyof GetHomeResponses];

export type StartRoundData = {
    body: StartRoundRequest;
    path?: never;
    query?: never;
    url: '/v1/rounds';
};

export type StartRoundErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request. ERR_NOT_ENOUGH_CARDS: Too few reviewed cards can be dealt for a round.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type StartRoundError = StartRoundErrors[keyof StartRoundErrors];

export type StartRoundResponses = {
    /**
     * OK
     */
    200: RoundPayload;
};

export type StartRoundResponse = StartRoundResponses[keyof StartRoundResponses];

export type GetRoundData = {
    body?: never;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}';
};

export type GetRoundErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type GetRoundError = GetRoundErrors[keyof GetRoundErrors];

export type GetRoundResponses = {
    /**
     * OK
     */
    200: RoundPayload;
};

export type GetRoundResponse = GetRoundResponses[keyof GetRoundResponses];

export type RecordAnswersData = {
    body: AnswersRequest;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/answers';
};

export type RecordAnswersErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type RecordAnswersError = RecordAnswersErrors[keyof RecordAnswersErrors];

export type RecordAnswersResponses = {
    /**
     * Done; no body.
     */
    204: void;
};

export type RecordAnswersResponse = RecordAnswersResponses[keyof RecordAnswersResponses];

export type FinishRoundData = {
    body: AnswersRequest;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/finish';
};

export type FinishRoundErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type FinishRoundError = FinishRoundErrors[keyof FinishRoundErrors];

export type FinishRoundResponses = {
    /**
     * OK
     */
    200: RoundSummary;
};

export type FinishRoundResponse = FinishRoundResponses[keyof FinishRoundResponses];

export type GetRoundSummaryData = {
    body?: never;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/summary';
};

export type GetRoundSummaryErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
};

export type GetRoundSummaryError = GetRoundSummaryErrors[keyof GetRoundSummaryErrors];

export type GetRoundSummaryResponses = {
    /**
     * OK
     */
    200: RoundSummary;
};

export type GetRoundSummaryResponse = GetRoundSummaryResponses[keyof GetRoundSummaryResponses];

export type GetRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/records';
};

export type GetRecordsErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetRecordsError = GetRecordsErrors[keyof GetRecordsErrors];

export type GetRecordsResponses = {
    /**
     * OK
     */
    200: RecordsView;
};

export type GetRecordsResponse = GetRecordsResponses[keyof GetRecordsResponses];

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/history';
};

export type GetHistoryErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors];

export type GetHistoryResponses = {
    /**
     * OK
     */
    200: History;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type GetVocabData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/vocab';
};

export type GetVocabErrors = {
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type GetVocabError = GetVocabErrors[keyof GetVocabErrors];

export type GetVocabResponses = {
    /**
     * OK
     */
    200: VocabHub;
};

export type GetVocabResponse = GetVocabResponses[keyof GetVocabResponses];

export type StartVocabSessionData = {
    body: StartVocabSessionRequest;
    path?: never;
    query?: never;
    url: '/v1/vocab/sessions';
};

export type StartVocabSessionErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type StartVocabSessionError = StartVocabSessionErrors[keyof StartVocabSessionErrors];

export type StartVocabSessionResponses = {
    /**
     * OK
     */
    200: VocabSession;
};

export type StartVocabSessionResponse = StartVocabSessionResponses[keyof StartVocabSessionResponses];

export type RecordVocabAnswersData = {
    body: VocabAnswersRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/v1/vocab/sessions/{sessionId}/answers';
};

export type RecordVocabAnswersErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_SESSION_NOT_FOUND: No vocabulary session has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_SESSION_CLOSED: That vocabulary session has finished and takes no new answer.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type RecordVocabAnswersError = RecordVocabAnswersErrors[keyof RecordVocabAnswersErrors];

export type RecordVocabAnswersResponses = {
    /**
     * Done; no body.
     */
    204: void;
};

export type RecordVocabAnswersResponse = RecordVocabAnswersResponses[keyof RecordVocabAnswersResponses];

export type FinishVocabSessionData = {
    body: VocabAnswersRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/v1/vocab/sessions/{sessionId}/finish';
};

export type FinishVocabSessionErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_SESSION_NOT_FOUND: No vocabulary session has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_SESSION_CLOSED: That vocabulary session has finished and takes no new answer.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type FinishVocabSessionError = FinishVocabSessionErrors[keyof FinishVocabSessionErrors];

export type FinishVocabSessionResponses = {
    /**
     * OK
     */
    200: VocabSummary;
};

export type FinishVocabSessionResponse = FinishVocabSessionResponses[keyof FinishVocabSessionResponses];

export type DeleteVocabCardData = {
    body?: never;
    path: {
        cardId: string;
    };
    query?: never;
    url: '/v1/vocab/cards/{cardId}';
};

export type DeleteVocabCardErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation. ERR_CARD_NOT_PERSONAL: That card is the catalog's; only a card made from a talk can be deleted.
     */
    403: ErrorResponse;
    /**
     * ERR_CARD_NOT_FOUND: No vocabulary card of the learner's own has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type DeleteVocabCardError = DeleteVocabCardErrors[keyof DeleteVocabCardErrors];

export type DeleteVocabCardResponses = {
    /**
     * Done; no body.
     */
    204: void;
};

export type DeleteVocabCardResponse = DeleteVocabCardResponses[keyof DeleteVocabCardResponses];

export type GetTalkData = {
    body?: never;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}';
};

export type GetTalkErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
};

export type GetTalkError = GetTalkErrors[keyof GetTalkErrors];

export type GetTalkResponses = {
    /**
     * OK
     */
    200: TalkView;
};

export type GetTalkResponse = GetTalkResponses[keyof GetTalkResponses];

export type StartTalkData = {
    body: StartTalkRequest;
    path?: never;
    query?: never;
    url: '/v1/talks';
};

export type StartTalkErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_MODEL_UNAVAILABLE: The language model gave no usable answer; send the request again.
     */
    503: ErrorResponse;
};

export type StartTalkError = StartTalkErrors[keyof StartTalkErrors];

export type StartTalkResponses = {
    /**
     * OK
     */
    200: TalkOpened;
};

export type StartTalkResponse = StartTalkResponses[keyof StartTalkResponses];

export type SendTurnData = {
    body: TurnRequest;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}/turns';
};

export type SendTurnErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_TALK_CLOSED: That talk has finished or ended and takes no more turns.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
};

export type SendTurnError = SendTurnErrors[keyof SendTurnErrors];

export type SendTurnResponses = {
    /**
     * OK
     */
    200: TurnResult;
};

export type SendTurnResponse = SendTurnResponses[keyof SendTurnResponses];

export type RetryReplyData = {
    body?: never;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}/reply';
};

export type RetryReplyErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_TALK_CLOSED: That talk has finished or ended and takes no more turns.
     */
    409: ErrorResponse;
    /**
     * ERR_MODEL_UNAVAILABLE: The language model gave no usable answer; send the request again.
     */
    503: ErrorResponse;
};

export type RetryReplyError = RetryReplyErrors[keyof RetryReplyErrors];

export type RetryReplyResponses = {
    /**
     * OK
     */
    200: PartnerReply;
};

export type RetryReplyResponse = RetryReplyResponses[keyof RetryReplyResponses];

export type RecordRecitalData = {
    body: RecitalRequest;
    path: {
        talkId: string;
        turn: number;
    };
    query?: never;
    url: '/v1/talks/{talkId}/turns/{turn}/recital';
};

export type RecordRecitalErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
};

export type RecordRecitalError = RecordRecitalErrors[keyof RecordRecitalErrors];

export type RecordRecitalResponses = {
    /**
     * Done; no body.
     */
    204: void;
};

export type RecordRecitalResponse = RecordRecitalResponses[keyof RecordRecitalResponses];

export type EndTalkData = {
    body?: never;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}/end';
};

export type EndTalkErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
};

export type EndTalkError = EndTalkErrors[keyof EndTalkErrors];

export type EndTalkResponses = {
    /**
     * OK
     */
    200: TalkEnded;
};

export type EndTalkResponse = EndTalkResponses[keyof EndTalkResponses];

export type MakeCandidatesData = {
    body?: never;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}/candidates';
};

export type MakeCandidatesErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read. ERR_MODEL_UNAVAILABLE: The language model gave no usable answer; send the request again.
     */
    503: ErrorResponse;
};

export type MakeCandidatesError = MakeCandidatesErrors[keyof MakeCandidatesErrors];

export type MakeCandidatesResponses = {
    /**
     * OK
     */
    200: CardCandidates;
};

export type MakeCandidatesResponse = MakeCandidatesResponses[keyof MakeCandidatesResponses];

export type AddCardsData = {
    body: AddCardsRequest;
    path: {
        talkId: string;
    };
    query?: never;
    url: '/v1/talks/{talkId}/cards';
};

export type AddCardsErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round, the talk, the settings or the profile it names.
     */
    400: ErrorResponse;
    /**
     * ERR_UNAUTHENTICATED: The request carries no valid access token.
     */
    401: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_TALK_NOT_FOUND: No talk has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type AddCardsError = AddCardsErrors[keyof AddCardsErrors];

export type AddCardsResponses = {
    /**
     * OK
     */
    200: CardCandidates;
};

export type AddCardsResponse = AddCardsResponses[keyof AddCardsResponses];
