// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type RoundKind = 'placement' | 'today' | 'yesterday' | 'extra';

export type Pass = 'first' | 'retry';

export type AnswerResult = 'ok' | 'ng' | 'timeout';

export type SubtopicRef = {
    topic: string;
    subtopic: string;
};

export type Settings = {
    topics: Array<string>;
    focus: Array<SubtopicRef>;
    dailySize: 5 | 10 | 15 | 20 | 30;
    sound: boolean;
};

export type Dot = {
    day: string;
    state: 'done' | 'gap' | 'missed' | 'upcoming';
};

export type RingProgress = {
    from: number;
    to: number;
    done: number;
    span: number;
};

export type ReachTopic = {
    id: string;
    name: string;
    count: number;
    added: number;
    ring: RingProgress;
};

export type ReachView = {
    topics: Array<ReachTopic>;
    nearest: {
        name: string;
        remaining: number;
    } | null;
};

export type StartRoundRequest = {
    roundId: string;
    kind: RoundKind;
};

export type Answer = {
    id: string;
    cardId: string;
    pass: Pass;
    result: AnswerResult;
    elapsedMs: number;
};

export type AnswersRequest = {
    answers: Array<Answer>;
};

export type SettingsPatch = {
    topics?: Array<string>;
    focus?: Array<SubtopicRef>;
    dailySize?: 5 | 10 | 15 | 20 | 30;
    sound?: boolean;
};

export type DrillCard = {
    id: string;
    topic: string;
    subtopic: string;
    level: number;
    words: number;
    prompt: string;
    text: string;
    alternatives: Array<string>;
    explanation: string;
    limitMs: number;
};

export type RoundPayload = {
    id: string;
    kind: RoundKind;
    day: string;
    portionDay: string | null;
    deck: Array<string>;
    cards: {
        [key: string]: DrillCard;
    };
    answered: Array<{
        cardId: string;
        pass: Pass;
        result: AnswerResult;
    }>;
    offset: number;
    total: number;
    retries: boolean;
};

export type GrowthRow = {
    cardId: string;
    prompt: string | null;
    kind: 'faster' | 'fixed';
    deltaMs: number;
};

export type Growth = {
    faster: number;
    fixed: number;
    compared: number;
    firstTime: number;
    rows: Array<GrowthRow>;
};

export type ReviewRow = {
    cardId: string;
    prompt: string | null;
};

export type TotalsView = {
    said: number;
    practicedDays: number;
    last14: Array<{
        day: string;
        count: number;
    }>;
    added: number;
};

export type RoundSummary = {
    roundId: string;
    kind: RoundKind;
    day: string;
    yesterday: boolean;
    placement: {
        level: number;
        toeic: string;
        first: boolean;
    } | null;
    growth: Growth;
    review: Array<ReviewRow>;
    streak: {
        value: number;
        restart: boolean;
        changed: boolean;
    };
    week: Array<Dot>;
    filled: string | null;
    difficulty: {
        change: 'up' | 'down';
        toeic: string;
    } | null;
    reach: ReachView;
    titles: Array<string>;
    topicNames: {
        [key: string]: string;
    };
    points: {
        earned: number;
        total: number;
    };
    totals: TotalsView;
    portionCompleted: boolean;
    todayOpen: boolean;
    continueToday: boolean;
};

export type SettingsView = {
    settings: Settings;
    removedFocus: Array<SubtopicRef>;
    completedToday: boolean;
};

export type StreakView = {
    kind: 'count';
    value: number;
    yesterdayGap: boolean;
} | {
    kind: 'restart';
    longest: number;
};

export type HomeState = {
    kind: 'onboarding';
} | {
    kind: 'placement';
} | {
    kind: 'ready';
    streak: StreakView;
} | {
    kind: 'recover-offer';
    streak: StreakView;
} | {
    kind: 'in-progress';
    portion: 'today' | 'yesterday';
    progress: number;
    target: number;
    resumeKind: RoundKind;
    streak: StreakView;
} | {
    kind: 'done';
    restoresTo: number | null;
    streak: StreakView;
} | {
    kind: 'not-enough';
    available: number;
    streak: StreakView;
};

export type HomePreview = {
    size: number;
    setting: number;
    shortage: boolean;
    reviewCount: number;
    newCount: number;
    focusNames: Array<string>;
    minutes: number;
};

export type HomeView = {
    state: HomeState;
    week: Array<Dot>;
    preview?: HomePreview;
    todayRounds: number;
    todayCards: number;
    todayLastRoundId?: string;
    dailySize: number;
    sound: boolean;
    contentError: boolean;
};

export type BreakdownTopic = {
    id: string;
    name: string;
    subtopics: Array<{
        id: string;
        name: string;
        count: number;
    }>;
};

export type TitleGroup = {
    kind: 'streak';
    values: Array<number>;
} | {
    kind: 'reach';
    topic: string;
    name: string;
    values: Array<number>;
};

export type RecordsView = {
    reach: ReachView;
    breakdown: Array<BreakdownTopic>;
    toeic: string | null;
    streak: {
        current: number;
        longest: number;
    };
    calendar: Array<Array<Dot>>;
    said: number;
    practicedDays: number;
    points: number;
    titles: Array<TitleGroup>;
};

export type TopicInfo = {
    id: string;
    name: string;
    subtopics: Array<{
        id: string;
        name: string;
    }>;
};

export type SettingsPageView = {
    settings: Settings;
    topics: Array<TopicInfo>;
    toeic: string | null;
};

export type History = {
    seenIds: Array<string>;
    topics: Array<string>;
    focusSubtopics: Array<string>;
    estimatedLevel: number;
};

export type ErrorResponse = {
    error: {
        code: string;
        message: string;
    };
};

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetSettingsError = GetSettingsErrors[keyof GetSettingsErrors];

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsPageView;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: SettingsPatch;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type UpdateSettingsErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round or the settings it names.
     */
    400: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: SettingsView;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetHomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/home';
};

export type GetHomeErrors = {
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetHomeError = GetHomeErrors[keyof GetHomeErrors];

export type GetHomeResponses = {
    /**
     * OK
     */
    200: HomeView;
};

export type GetHomeResponse = GetHomeResponses[keyof GetHomeResponses];

export type StartRoundData = {
    body: StartRoundRequest;
    path?: never;
    query?: never;
    url: '/v1/rounds';
};

export type StartRoundErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round or the settings it names.
     */
    400: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request. ERR_NOT_ENOUGH_CARDS: Too few reviewed cards can be dealt for a round.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type StartRoundError = StartRoundErrors[keyof StartRoundErrors];

export type StartRoundResponses = {
    /**
     * OK
     */
    200: RoundPayload;
};

export type StartRoundResponse = StartRoundResponses[keyof StartRoundResponses];

export type RecordAnswersData = {
    body: AnswersRequest;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/answers';
};

export type RecordAnswersErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round or the settings it names.
     */
    400: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type RecordAnswersError = RecordAnswersErrors[keyof RecordAnswersErrors];

export type RecordAnswersResponses = {
    /**
     * Done; no body.
     */
    204: void;
};

export type RecordAnswersResponse = RecordAnswersResponses[keyof RecordAnswersResponses];

export type FinishRoundData = {
    body: AnswersRequest;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/finish';
};

export type FinishRoundErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round or the settings it names.
     */
    400: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
    /**
     * ERR_CONFLICT: Another write to the same data kept winning; send the request again. ERR_ROUND_CLOSED: That round or day can no longer take this request.
     */
    409: ErrorResponse;
    /**
     * ERR_PAYLOAD_TOO_LARGE: The request body is too large.
     */
    413: ErrorResponse;
    /**
     * ERR_CONTENT_UNREADABLE: The card content could not be read.
     */
    503: ErrorResponse;
};

export type FinishRoundError = FinishRoundErrors[keyof FinishRoundErrors];

export type FinishRoundResponses = {
    /**
     * OK
     */
    200: RoundSummary;
};

export type FinishRoundResponse = FinishRoundResponses[keyof FinishRoundResponses];

export type GetRoundSummaryData = {
    body?: never;
    path: {
        roundId: string;
    };
    query?: never;
    url: '/v1/rounds/{roundId}/summary';
};

export type GetRoundSummaryErrors = {
    /**
     * ERR_BAD_REQUEST: The request does not fit the round or the settings it names.
     */
    400: ErrorResponse;
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
    /**
     * ERR_ROUND_NOT_FOUND: No round has that id.
     */
    404: ErrorResponse;
};

export type GetRoundSummaryError = GetRoundSummaryErrors[keyof GetRoundSummaryErrors];

export type GetRoundSummaryResponses = {
    /**
     * OK
     */
    200: RoundSummary;
};

export type GetRoundSummaryResponse = GetRoundSummaryResponses[keyof GetRoundSummaryResponses];

export type GetRecordsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/records';
};

export type GetRecordsErrors = {
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetRecordsError = GetRecordsErrors[keyof GetRecordsErrors];

export type GetRecordsResponses = {
    /**
     * OK
     */
    200: RecordsView;
};

export type GetRecordsResponse = GetRecordsResponses[keyof GetRecordsResponses];

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/history';
};

export type GetHistoryErrors = {
    /**
     * ERR_FORBIDDEN: The caller may not run this operation.
     */
    403: ErrorResponse;
};

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors];

export type GetHistoryResponses = {
    /**
     * OK
     */
    200: History;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];
